//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISI_Service_Desk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RISI_ServiceDeskEntities1 : DbContext
    {
        private static RISI_ServiceDeskEntities1 _context;

        public RISI_ServiceDeskEntities1()
            : base("name=RISI_ServiceDeskEntities1")
        {
        }

        public static RISI_ServiceDeskEntities1 GetContext()
        {
            if (_context == null)
                _context = new RISI_ServiceDeskEntities1();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Clients { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
